version: '3.7'
services:
  postgres:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  
  amq:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 61613:61613
      - 61616:61616
      - 8161:8161
      - 5672:5672
    #definition mount point
    volumes:
      - ../data/adapt/amq/data:/opt/activemq/data
      - ../data/adapt/amq/conf:/opt/activemq/conf
        #- ../data/var/log/activemq:/var/log/activemq
    # 

